classes: {
  server: {
    style: {
      fill: "#023047"
      font-color: white
      stroke-width: 0
    }
  }

  fx: {
    style: {
      fill: "#FFB703"
      stroke-width: 0
    }
  }

  kit: {
    style: {
      fill: "#FB8500"
      stroke-width: 0
    }
  }

  ui: {
    style: {
      fill: "#8ECAE6"
      stroke-width: 0
    }
  }

  build: {
    style: {
      fill: "#219EBC"
      stroke-width: 0
    }
  }
}

Express.class: server
Fastify.class: server
h3.class: server
Hono.class: server

Nitro.class: fx
Vike.class: fx
Vinxi.class: fx

NestJS.class: kit
"Next.js".class: kit
Nuxt.class: kit
"Qwik City".class: kit
Remix.class: kit
SolidStart.class: kit
SvelteKit.class: kit
"TanStack Start".class: kit

Qwik.class: ui
React.class: ui
Solid.class: ui
Svelte.class: ui
"Vue.js".class: ui

Rspack.class: build
Webpack.class: build
esbuild.class: build
Rolldown.class: build
Rollup.class: build
SWC.class: build
Turbopack.class: build
Vite.class: build
Babel.class: build

SvelteKit -> Svelte
SvelteKit -> Vite

"Qwik City" -> Vite
"Qwik City" -> Qwik

Nuxt -> Vite
Nuxt -> Nitro
Nuxt -> "Vue.js"

SolidStart -> Vinxi
SolidStart -> Solid

Vinxi -> Vite
Vinxi -> Nitro

Vike -> Vite

Vite -> Rolldown
Vite -> esbuild
Vite -> Rollup

Nitro -> Rollup
Nitro -> h3 -> esbuild

"TanStack Start" -> React
"TanStack Start" -> "TanStack Router"
"TanStack Start" -> Vite
"TanStack Start" -> Vinxi

"Next.js" -> Webpack
"Next.js" -> Turbopack
"Next.js" -> React

Remix -> React
Remix -> "React Router"
Remix -> Vite

Hono -> esbuild

NestJS -> Express
NestJS -> Fastify

Webpack -> Babel
Webpack -> SWC

Rspack -> SWC
