Nitro
Vite

SvelteKit -> Vite
SvelteKit -> Svelte

Vike -> Vite

Vinxi -> Vite
Vinxi -> Nitro

SolidStart -> Solid
SolidStart -> Vinxi

Nuxt -> "Vue.js"
Nuxt -> Nitro
Nuxt -> Vite

Vite -> Rollup
Vite -> esbuild

Nitro -> Rollup
Nitro -> h3 -> esbuild
Nitro -> esbuild

Remix -> React
Remix -> "React Router"
Remix -> Vite

"Next.js" -> Webpack
"Next.js" -> React

Hono -> esbuild

"Qwik City" -> Qwik
"Qwik City" -> Vite
